### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by TeemuBergman** [KalleHahl/tiralabra#1]
**Projekti ladattu 19.2. klo 10.21**

- Ohjeistukseen sekä sovellukseen voisi lisätä ohjeen siitä, miten muuttujia käytetään. Sain sen kyllä tulkattua koodista, mutta tämä osuus voisi olla hieman selkeämpi.

- Sain virheellisen tuloksen laskusta jossa muuttuja `x=10`: `x+x=101010` sekä muissakin laskuissa, joissa samaa muuttujaa käytettiin enemmän kuin kerran. Tätä kannattaa tutkia.

- Funktiot `sin`, `cos` ja `tan` antoivat virheellisiä tuloksia, kun `sqrt` antoi oikeita tuloksia.

- Testejä on kirjoitettu laajalti, mutta niitä kannattaa laajentaa edelleen, jotta esimerkiksi edellä mainitut, `Variables` luokassa olevat ongelmat saadaan pidettyä kurissa.

- Tiedosto `conftest.py` oli tyhjä, joten kannattaako sitä versioida?

- Lisäisin projektiin myös tiedoston `.gitignore`, jonka avulla esimerkiksi turhat `__pycache__` kansiot saa pidettyä poissa versionhallinnasta.

- Projektin juuressa ei tarvitse olla tiedostoa `__init__.py`, mutta koodia sisältävissä alihakemistoissa kyllä, jotta `Pytest` pääsee testaamaan sen sisällön. 

- Testaus kohdistuu vain `tests` kansioon ja siellä oleviin testeihin, eikä varsinaisiin algoritmeihin. Käytä tiedostoa `.coveragerc` ja siellä olevalla komennolla `omit = src/**/__init__.py,src/tests/**,src/main.py` suodattamaan turhat testikohteet pois.

- Tiedosto `variables.py` kannattaa siirtää projektin juuresta samaan kansioon muiden algoritmien kanssa.

- Funktiot `to_postfix` sekä `count` suorittavat nyt monta toimintoa kerralla, eivätkä siten toteuta Single Responsibility Principle (SRP) periaatetta. Itse tekisin näistä kahdesta omat luokkansa, joiden sisään pilkkoisin olemassa olevat toiminnallisuudet moniin eri funktioihin ja metodeihin. Näin koodista saadaan yksinkertaista ja se pysyy mahdollisimman muokattavana. 

- Sovelluksen koodia on kauttaaltaan kommentoitu laajasti ja se on erittäin hyvä asia!

- Testasin projektia myös Windows 10 -ympäristössä. Tässä huomiona oli `invoke start` komennon yhteydessä tullut virheilmoitus `You indicated pty=True, but your platform doesn't support the 'pty' module!`, joka johtuu sen sisältämästä pty=True arvosta. Tämän muutettua arvoon False, tuli seuraavaksi virheilmoitus `'python3' is not recognized as an internal or external command, operable program or batch file.` joka ratkeaa muuttamalla komennon muotoon `ctx.run('python src/index.py', pty=False)`. Voit halutessasi vilkaista minun vastaavaa repoa ja katsoa miten olen tämän saman ongelman ratkaissut, jotta `invoke start` toimii sekä Linuxilla että Windowsilla.

Kirjoittaessani tätä vertaisarviointia, oli projektia päivitetty, joten ehkä osa näistä havaituista ongelmista on jo korjattu. Hieman refaktorointia peliin ja hyvä projekti tästä tulee!

**Comment by KalleHahl** [comment]
Hei ja kiitos paljon palautteesta!

Olen tehnyt paljon muutoksia vertaisarviointisi perusteella. Luulen, että sin, cos ja tan funktioiden kohdalla
kyseessä on, että laskimen vastauksia on verrattu vastauksiin, joissa on laskettu asteita. Tällä hetkellä tässä projektissa on mahdollisuus laskea vain radiaaneina noita funktioita!
