### ISSUE TITLE
MyCoolIssue

### ISSUE THREAD

**Issue by astranero** [KalleHahl/tiralabra#2]
Feb 23 2023 14:27 Repository was pulled.

- The package structure seems good, python OOP and single-reponsibility principle seems to be upheld. Which is Bueno. 
- It might be good to add some pythonic Docstrings to explain what each method is supposed to do. For example what is returned in Class `ShuntingYard`'s method `to_postfix`.
-  Also in `to_postfix` method there is too many if-else statements in my opinion. You could wrap them into a dictionary. 
  `Somedict = {"+-": self.precedence_1}`  After that you could just try 
`
func = Somedict[self.char]()
`, and of course expect IndexError. 
- Otherwise project seems to be going well, good work. :+1:

**Comment by KalleHahl** [comment]
Thank you for the review!

I hastily changed the algorithms to use classes and hadn't had time to write any explanations to them. Docstrings are now included! I made the recommended changes to the ```to_postfix``` method and it made the code much clearer and more 'easy on the eyes', thank you for the tip!
